# Generated by Django 5.0.3 on 2024-04-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
