# Generated by Django 5.0.3 on 2024-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0005_tag_lesson_comment_course_tags_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
