# Generated by Django 5.0.3 on 2024-04-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0006_course_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='gender',
        ),
    ]
