# Generated by Django 5.0.3 on 2024-04-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0007_remove_course_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
    ]
