# Generated by Django 5.0.3 on 2024-04-16 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0009_course_image_lesson_image_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courseapp.category'),
        ),
    ]
